[package]
name = "rust_render"
version = "0.1.0"
authors = ["Eric Shaffer <shaffer1@illinois.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
